GET https://www.mapquestapi.com/geocoding/v1/address?key=5mSxW4DUx3kq2fzTIP5f3tQizva61zJQ
&location=Kuulankatu, Seinäjoki


###
POST https://www.mapquestapi.com/geocoding/v1/address?key=5mSxW4DUx3kq2fzTIP5f3tQizva61zJQ
Content-Type: application/json

{
    "location": "Boulder Colorado"
}